### ISSUE TITLE
Fatal error: Unable to find local grunt

### ISSUE THREAD

**Issue by 0x-r4bbit** [mbuchetics/heroku-buildpack-nodejs-grunt#4]
Hey @mbuchetics !

Using your heroku buildpack i'm getting the following error, after buildpack is fetched and installed:

Unable to find local grunt

`grunt` is defined in my `package.json` und `dependencies`. Is there anything else I'm missing?

**Comment by mzatko** [comment]
it is kind of schizophrenic behavior... :)
when installing local I'm getting message "npm WARN prefer global grunt-cli@0.1.13 should be installed with -g"
when I'm running it after installing global it's failing because of "Unable to find local grunt"
In fact, you need it on both local and global...
